# Docker Compose configuration version specification
version: '3'

# Service definitions for application components
services:

  # Backend API service configuration
  api-server:
    # Build setup using Dockerfile from backend directory
    build:
      context: /home/jusky/Documents/SPE-finalProjekt/mernapp/backend
      dockerfile: Dockerfile
    # Custom image name for container registry
    image: jusky/server
    # Port mapping for external access
    ports:
      - "5000:5000"
    # Volume configuration for log persistence
    volumes:
      - ./Desktop:/usr/src/app/logs
    # Network connectivity setup
    networks:
      - mern-app
    # Container identifier specification
    container_name: server
    # Startup command execution
    command: npm start

  # Frontend React application service
  react-app:
    # Build instructions from project root
    build:
      context: /home/jusky/Documents/SPE-finalProjekt/mernapp
      dockerfile: Dockerfile
    # Client-side image naming
    image: jusky/client
    # Keep STDIN open for interactive sessions
    stdin_open: true
    # Port exposure for web access
    ports:
      - "3000:3000"
    # Network association
    networks:
      - mern-app
    # Runtime command initialization
    command: npm start

# Network configuration for inter-service communication
networks:
  mern-app:
    # Network driver selection
    driver: bridge

# Backend API access endpoint: http://localhost:5000/
